### ISSUE TITLE
source.FixAll not working

### ISSUE THREAD

**Issue by braebo** [robole/stylelint-config-svelte-roboleary#1]
Hey there!  I've been using svelte with stylelint for awhile now, but it recently stopped working.  Format on save never works, and manually running it only works sometimes.

I'm curious if you've had success lately with stylelint in svelte?  I've tried countless different config/extension combinations with fresh projects and fresh VSCode installation, but I haven't been able to restore the functionality of formatting css/scss in svelte style tags on save 😅

I was hoping using this would help, but it seems to be facing the same issue.

**Comment by robole** [comment]
Yes, this configuration works with the latest version of stylelint (v14.1) and VS Code + latest extensions. 

Stylelint had breaking changes in v14, which now requires explicit declaration of which languages you want to lint. It is CSS by default. Check the section "migrating to v14" in [their repo](https://github.com/stylelint/stylelint) for an explanation.

I updated the README to outline the settings/extensions that I use in VS Code.

All the best
